In [7]:
import numpy as np

def mystats(data):
    wynik = np.median(data)
    return wynik

def trimmed_mean(data, p):
    arr = np.sort(np.array(data))
    n = len(arr)

    if isinstance(p, float) and 0 <= p < 0.5:
        odciecie = int(n*p)
    else:
        odciecie = int(p)

    arr = arr[odciecie:-odciecie]

    wynik2 = np.mean(arr)
    return wynik2

In [10]:
def main():
    lista_nieparzysta = [7, 1, 3, 4, 9, 2, 5]
    lista_parzysta = [10, 2, 3, 5, 7, 8]
    lista_z_odstajacymi = [1, 2,5 ,6, 10, 100]


    print(f'mediana z nieparzystej:  {mystats(lista_nieparzysta)}')
    print(f'mediana z parzystej {mystats(lista_parzysta)}')

    print(f'srednia ucinana z listy z odstajacymi wartosciami {trimmed_mean(lista_z_odstajacymi, p=1)}')

if __name__ == '__main__':
    main()

mediana z nieparzystej:  4.0
mediana z parzystej 6.0
srednia ucinana z listy z odstajacymi wartosciami 5.75

In [13]:
import pandas as pd

kolumny = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df = pd.read_csv('iris.data', names=kolumny)

cechy = df.drop(columns=['class'])
print("globalna wartość średnia")
print(cechy.mean())
print("globalna wartość mediana")
print(cechy.median())
print("globalne odchylenie standardowe")
print(cechy.std())

print("statystyki dla kazdego irysa oddzielnie")
statystyki_grupowe = df.groupby('class').agg(['mean', 'median', 'std'])

display(statystyki_grupowe)

globalna wartość średnia
sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64
globalna wartość mediana
sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64
globalne odchylenie standardowe
sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
dtype: float64
statystyki dla kazdego irysa oddzielnie

                sepal_length                  sepal_width                   \
                        mean median       std        mean median       std
class
Iris-setosa            5.006    5.0  0.352490       3.418    3.4  0.381024
Iris-versicolor        5.936    5.9  0.516171       2.770    2.8  0.313798
Iris-virginica         6.588    6.5  0.635880       2.974    3.0  0.322497

                petal_length                  petal_width
                        mean median       std        mean median       std
class
Iris-setosa            1.464   1.50  0.173511       0.244    0.2  0.107210
Iris-versicolor        4.260   4.35  0.469911       1.326    1.3  0.197753
Iris-virginica         5.552   5.55  0.551895       2.026    2.0  0.274650

In [19]:
import pandas as pd

df_red = pd.read_csv('winequality-red.csv', sep=';')
df_white = pd.read_csv('winequality-white.csv', sep=';')

df_red['color'] = 'red'
df_white['color'] = 'white'

df_wine = pd.concat([df_red, df_white], ignore_index=True)

df_wine.columns = df_wine.columns.str.replace(' ', '_')

print("zadanie 4")
cechy_bez_targetu = df_wine.drop(columns=['quality', 'color'])

print("\nwariancja cech posortowana rosnąco:")
wariancja_cech = cechy_bez_targetu.var().sort_values(ascending=True)
print(wariancja_cech)

print("\nwariancja cech dla każdej unikalnej wartości cechy quality:")
wariancja_po_quality = df_wine.drop(columns=['color']).groupby('quality').var()
display(wariancja_po_quality)

print("\nuśredniona wariancja ze wszystkich cech dla każdej wartości cechy quality':")
srednia_wariancja_quality = wariancja_po_quality.mean(axis=1)
print(srednia_wariancja_quality)

print("\nodchylenie standardowe z podziałem na kolor wina:")
odchylenie_po_kolorze = df_wine.drop(columns=['quality']).groupby('color').std()
display(odchylenie_po_kolorze)

print("\nzadanie 5")
kwartyle = cechy_bez_targetu.quantile([0.25, 0.50, 0.75])
display(kwartyle)

print("\nzadanie 6")
percentyl_95 = df_wine['residual_sugar'].quantile(0.95)
powyzej_95 = df_wine[df_wine['residual_sugar'] > percentyl_95]
display(powyzej_95)

zadanie 4

wariancja cech posortowana rosnąco:
density                    0.000009
chlorides                  0.001227
citric_acid                0.021117
sulphates                  0.022143
pH                         0.025853
volatile_acidity           0.027105
alcohol                    1.422561
fixed_acidity              1.680740
residual_sugar            22.636696
free_sulfur_dioxide      315.041192
total_sulfur_dioxide    3194.720039
dtype: float64

wariancja cech dla każdej unikalnej wartości cechy quality:

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
3,3.054989,0.116904,0.030106,22.379724,0.003846,3598.839368,12575.774713,0.000008,0.045474,0.016127,1.224336
4,1.599783,0.052584,0.033153,14.532382,0.002215,355.908005,3755.571054,0.000006,0.035491,0.027039,0.972044
5,1.587604,0.031891,0.025737,24.943144,0.001765,344.677016,3694.555990,0.000006,0.024768,0.020064,0.663273
6,1.667174,0.021632,0.020306,23.894861,0.000951,283.434310,3075.189393,0.000009,0.025921,0.021533,1.268983
7,1.882771,0.013641,0.012426,16.323577,0.000475,222.763414,2298.599952,0.000009,0.025487,0.025740,1.438410
8,1.316148,0.014246,0.010495,17.434524,0.000246,295.677245,1775.378576,0.000008,0.024782,0.027520,1.635640
9,0.967000,0.003320,0.006730,14.132000,0.000055,180.300000,393.000000,0.000010,0.006870,0.008580,1.027000

uśredniona wariancja ze wszystkich cech dla każdej wartości cechy quality':
quality
3    1472.862327
4     375.339432
5     369.684660
6     307.776825
7     231.007809
8     190.138130
9      53.586506
dtype: float64

odchylenie standardowe z podziałem na kolor wina:

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol
color,,,,,,,,,,,
red,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668
white,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621

zadanie 5

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol
0.25,6.4,0.23,0.25,1.8,0.038,17.0,77.0,0.99234,3.11,0.43,9.5
0.50,7.0,0.29,0.31,3.0,0.047,29.0,118.0,0.99489,3.21,0.51,10.3
0.75,7.7,0.40,0.39,8.1,0.065,41.0,156.0,0.99699,3.32,0.60,11.3

zadanie 6

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color
480,10.6,0.280,0.39,15.50,0.069,6.0,23.0,1.00260,3.12,0.66,9.20,5,red
1434,10.2,0.540,0.37,15.40,0.214,55.0,95.0,1.00369,3.18,0.77,9.00,6,red
1435,10.2,0.540,0.37,15.40,0.214,55.0,95.0,1.00369,3.18,0.77,9.00,6,red
1599,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.80,6,white
1606,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.80,6,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6290,6.9,0.190,0.31,19.25,0.043,38.0,167.0,0.99954,2.93,0.52,9.10,7,white
6293,6.9,0.190,0.31,19.25,0.043,38.0,167.0,0.99954,2.93,0.52,9.10,7,white
6347,6.1,0.340,0.24,18.35,0.050,33.0,184.0,0.99943,3.12,0.61,9.30,5,white
6348,6.2,0.350,0.25,18.40,0.051,28.0,182.0,0.99946,3.13,0.62,9.30,6,white
6377,5.8,0.315,0.19,19.40,0.031,28.0,106.0,0.99704,2.97,0.40,10.55,6,white